### ISSUE TITLE
Healthbar only updates from player-dealt damage.

### ISSUE THREAD

**Issue by Estecka** [Vanderflys/CustomHealthbar#1]
Hi,

I wanted to use the datapack in singleplayer to track the health of other mobs. In particular, free-roaming villagers who may passively loose health due to their poor life choices.

Their healthbar only seem to update when the damages are coming from me. All other damage sources I have tested do nothing: Fire, gravity, suffocation and mob infighting.

After I hit the already damaged mob, the healthbar updates to the correct amount of health, but the damage display will also include all previously accumulated damages.

I haven't changed any of the default settings.

**Versions:**
- Minecraft 1.20.6 (vanilla)
- CustomHealthBar v2.2.1 (datapack version)

**Comment by Estecka** [comment]
The healthbar also doesn't update when the entity is healed with a splash potion, even thrown by me.

**Comment by Vanderflys** [comment]
Yes, I did this to limit the amount of ticking entities to reduce the lag you can get.
If the healthbar did update every time an entity gets damaged (so by natural causes), then the datapack would run a lot more commands for each entity while their health may not have even changed. This causes the TPS to decrease thus making the game have more lag. Unless you want to know, I am not going deeper into how the datapack works. If that is the case, please join the Discord Support Server on the Modrinth page.
